### ISSUE TITLE
query() and get() method implementation is limiting

### ISSUE THREAD

**Issue by Botono** [roylines/node-angular-rest#1]
First of all, I love this module.  It really simplifies routing with Express and Angular, and thank you for writing it.

The only issue I have found so far is really a conceptual one.  My app has a special case where an API binding only ever returns 1 record, so I use the get() method to access it, but it doesn't used the /:id grammar because it only ever returns one record (it's basically a stack:  the app will call it, get a record, save the record and call it again to get the next record).

However, since I'm not using /:id, the get method is routed to the query() method on the server.

It's a small issue, which I overcame by simply putting my code in the query() method, but I wanted you to be aware of it.

Thanks again for the great module.

**Comment by roylines** [comment]
If I understand correctly you are implementing a stack. If the endpoint item was "stack", would it make sense to use something like:

```
wget http://myurl/stack/pop
```

or 

```
wget http://myurl/stack/next
```

to get the next item off the stack? This would be a special case of the :id attribute, and would route correctly.

It would allow you also to support taking from the start or end of the queue by using a special :id attribute.

Thanks for your comments, they have been very useful.
