### ISSUE TITLE
No built-in support for POSTs to /endpoint

### ISSUE THREAD

**Issue by Botono** [roylines/node-angular-rest#2]
The current state of this module lacks support for sending POST requests to /endpoint, which is a REST standard for creating new records (PUT to /endpoint/:id for updates, POST to /endpoint for creating).

I made an update in my fork which handles this scenario simply by adding one more bind() call in angular-resource.js, but my commits don't look very clean (my IDE made changes to spacing and whatnot), so I decided against making a pull request.

**Comment by roylines** [comment]
available in npm as version 0.1.1
